name: Convert Website to APK

on:
  workflow_dispatch:
    inputs:
      website_url:
        description: 'URL of the website to convert to APK'
        required: true
        default: 'https://example.com'

jobs:
  convert-to-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip

    - name: Download and install Android SDK
      run: |
        # Create base directories
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools

        # Download Android SDK Command Line Tools
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        
        # Extract files into cmdline-tools folder
        unzip sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        rm sdk-tools.zip

        # Set environment variables
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

        # Accept licenses and install necessary components
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Create Android project structure
      run: |
        mkdir -p PeDitX/app/src/main/res
        mkdir -p PeDitX/app/src/main/java/com/peditx/app

        # Create AndroidManifest.xml
        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
        <manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"
            package=\"com.peditx.app\">
            <application
                android:allowBackup=\"true\"
                android:icon=\"@mipmap/ic_launcher\"
                android:label=\"PeDitX\"
                android:roundIcon=\"@mipmap/ic_launcher_round\"
                android:supportsRtl=\"true\"
                android:theme=\"@style/Theme.AppCompat.Light.NoActionBar\">
                <activity android:name=\".MainActivity\"
                    android:theme=\"@style/Theme.AppCompat.Light.NoActionBar\">
                    <intent-filter>
                        <action android:name=\"android.intent.action.MAIN\" />
                        <category android:name=\"android.intent.category.LAUNCHER\" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>" > PeDitX/app/src/main/AndroidManifest.xml

        # Create MainActivity.java
        echo "package com.peditx.app;

        import android.os.Bundle;
        import android.webkit.WebSettings;
        import android.webkit.WebView;
        import android.webkit.WebViewClient;
        import androidx.appcompat.app.AppCompatActivity;

        public class MainActivity extends AppCompatActivity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                WebView webView = new WebView(this);
                WebSettings webSettings = webView.getSettings();
                webSettings.setJavaScriptEnabled(true);
                webSettings.setDomStorageEnabled(true);
                webView.setWebViewClient(new WebViewClient());
                webView.loadUrl(\"${{ github.event.inputs.website_url }}\");
                setContentView(webView);
            }
        }" > PeDitX/app/src/main/java/com/peditx/app/MainActivity.java

        # Create build.gradle for app
        echo "plugins {
            id 'com.android.application'
        }

        android {
            compileSdkVersion 30
            defaultConfig {
                applicationId \"com.peditx.app\"
                minSdkVersion 21
                targetSdkVersion 30
                versionCode 1
                versionName \"1.0\"
            }
            buildTypes {
                release {
                    minifyEnabled false
                    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                }
            }
        }

        dependencies {
            implementation 'androidx.appcompat:appcompat:1.3.1'
            implementation 'androidx.constraintlayout:constraintlayout:2.1.0'
}" > PeDitX/app/build.gradle

        # Create settings.gradle
        echo "include ':app'" > PeDitX/settings.gradle

        # Create gradle.properties
        echo "org.gradle.jvmargs=-Xmx2048m" > PeDitX/gradle.properties

        # Create gradle wrapper
        cd PeDitX
        gradle wrapper --gradle-version 7.0.2

    - name: Build APK
      run: |
        cd PeDitX
        ./gradlew assembleDebug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: PeDitX
        path: PeDitX/app/build/outputs/apk/debug/app-debug.apk
