name: Convert Website to APK

on:
  workflow_dispatch:
    inputs:
      website_url:
        description: 'URL of the website to convert to APK'
        required: true
        default: 'http://peditxrt.lan/'

jobs:
  convert-to-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip

    - name: Download and install Android SDK
      run: |
        # Create directories for Android SDK
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        cd $HOME/android-sdk
        
        # Download Android SDK command line tools
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip sdk-tools.zip -d cmdline-tools/latest
        rm sdk-tools.zip

        # Set environment variables
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        
        # Install required components
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Verify SDK installation
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        sdkmanager --list

    - name: Set up Android project
      run: |
        mkdir -p PeDitX
        cd PeDitX
        curl -o gradle-wrapper.zip https://services.gradle.org/distributions/gradle-7.3.3-bin.zip
        unzip gradle-wrapper.zip
        mkdir -p app/src/main/{java/com/peditx/app,res/drawable,res/layout}
        
        # Add splash screen image
        curl -o app/src/main/res/drawable/splash.png https://raw.githubusercontent.com/peditx/iranIPS/refs/heads/main/.files/apps/splash.png

        # Add AndroidManifest.xml
        cat <<EOL > app/src/main/AndroidManifest.xml
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.peditx.app">
            <application
                android:allowBackup="true"
                android:icon="@drawable/splash"
                android:label="PeDitX"
                android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                <activity android:name=".SplashActivity">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOL

        # Add SplashActivity.java
        cat <<EOL > app/src/main/java/com/peditx/app/SplashActivity.java
        package com.peditx.app;

        import android.content.Intent;
        import android.os.Bundle;
        import android.os.Handler;
        import androidx.appcompat.app.AppCompatActivity;

        public class SplashActivity extends AppCompatActivity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                setContentView(R.layout.activity_splash);

                new Handler().postDelayed(() -> {
                    startActivity(new Intent(SplashActivity.this, MainActivity.class));
                    finish();
                }, 3000); // 3 seconds delay
            }
        }
        EOL

        # Add MainActivity.java
        cat <<EOL > app/src/main/java/com/peditx/app/MainActivity.java
        package com.peditx.app;

        import android.os.Bundle;
        import android.webkit.WebSettings;
        import android.webkit.WebView;
        import android.webkit.WebViewClient;
        import androidx.appcompat.app.AppCompatActivity;

        public class MainActivity extends AppCompatActivity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                WebView webView = new WebView(this);
                WebSettings webSettings = webView.getSettings();
                webSettings.setJavaScriptEnabled(true);
                webSettings.setDomStorageEnabled(true);
                webView.setWebViewClient(new WebViewClient());
                webView.loadUrl("${{ github.event.inputs.website_url }}");
                setContentView(webView);
            }
        }
        EOL

        # Add build.gradle for the app
        cat <<EOL > app/build.gradle
        plugins {
            id 'com.android.application'
        }

        android {
            compileSdkVersion 30
            defaultConfig {
                applicationId "com.peditx.app"
                minSdkVersion 21
                targetSdkVersion 30
                versionCode 1
                versionName "1.0"
            }
            buildTypes {
                release {
                    minifyEnabled false
                }
            }
        }

        dependencies {
            implementation 'androidx.appcompat:appcompat:1.2.0'
            implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
        }
        EOL

        # Add gradle-wrapper.properties
        cat <<EOL > gradle/wrapper/gradle-wrapper.properties
        distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip
        EOL

    - name: Build APK
      run: |
        cd PeDitX
        ./gradlew assembleDebug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: PeDitX
        path: PeDitX/app/build/outputs/apk/debug/app-debug.apk
