name: Build PeDitX APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      # 1. دریافت سورس کد
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. راه‌اندازی Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. نصب Bubblewrap CLI
      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      # 4. نصب OpenJDK 17 و تنظیم JAVA_HOME
      - name: Install OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      # 5. دانلود تصاویر آیکون و اسپلش
      - name: Download icon and splash images
        run: |
          wget -O icon.png "https://raw.githubusercontent.com/peditx/iranIPS/refs/heads/main/.files/apps/icon-512x512.png"
          wget -O splash.png "https://raw.githubusercontent.com/peditx/iranIPS/refs/heads/main/.files/apps/splash.png"

      # 6. ایجاد فایل پیکربندی Bubblewrap
      - name: Create bubblewrap configuration
        run: |
          cat <<'EOF' > bubblewrap-config.json
          {
            "manifestUrl": "http://peditxos.lan",
            "name": "PeDitX",
            "launcherName": "PeDitX",
            "packageId": "com.example.peditx",
            "versionCode": 1,
            "appVersion": "1.0.0",
            "startUrl": "/",
            "themeColor": "#000000",
            "navigationColor": "#000000",
            "display": "standalone",
            "icons": {
              "android": "icon.png"
            },
            "splashScreen": {
              "image": "splash.png",
              "backgroundColor": "#FFFFFF"
            },
            "generated": {
              "jdkPath": "/usr/lib/jvm/java-17-openjdk-amd64",
              "androidSdkPath": "/home/runner/.bubblewrap/android_sdk"
            }
          }
          EOF

      # 7. اجرای bubblewrap init به صورت غیرتعاملی
      - name: Initialize Bubblewrap project
        run: |
          export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
          echo "Using JAVA_HOME: $JAVA_HOME"
          bubblewrap init --overwrite --config=bubblewrap-config.json <<EOF
          No
          Y
          Y
          $JAVA_HOME
          EOF

      # 8. ساخت APK
      - name: Build APK using Bubblewrap
        run: bubblewrap build

      # 9. ایجاد ریلیز در GitHub
      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0
          release_name: "PeDitX APK Release v1.0.0"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      # 10. آپلود فایل APK به ریلیز
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/app-release-signed.apk
          asset_name: PeDitX.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
