name: Build PeDitX APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      # Use official Android setup action for reliable SDK installation
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Download icon and splash images
        run: |
          wget -O icon.png "https://raw.githubusercontent.com/peditx/iranIPS/main/.files/apps/icon-512x512.png"
          wget -O splash.png "https://raw.githubusercontent.com/peditx/iranIPS/main/.files/apps/splash.png"

      - name: Create bubblewrap configuration
        run: |
          cat <<'EOF' > bubblewrap-config.json
          {
            # Use valid public URL for TWA manifest
            "manifestUrl": "https://peditx.github.io/manifest.json",
            "name": "PeDitX",
            "launcherName": "PeDitX",
            "packageId": "com.example.peditx",
            "versionCode": 1,
            "appVersion": "1.0.0",
            "startUrl": "/",
            "themeColor": "#000000",
            "navigationColor": "#000000",
            "display": "standalone",
            "icons": {
              "android": "icon.png"
            },
            "splashScreen": {
              "image": "splash.png",
              "backgroundColor": "#FFFFFF"
            }
          }
          EOF

      # Initialize project without interactive prompts
      - name: Initialize Bubblewrap project
        run: |
          bubblewrap init --non-interactive --config=bubblewrap-config.json
          # Accept licenses automatically
          yes | bubblewrap license --accept

      - name: Build APK using Bubblewrap
        run: bubblewrap build

      # Correct APK path (default is current directory)
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/release/*.apk
          asset_name: PeDitX-v1.0.0.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
