name: Generate Keystore

on: [push, workflow_dispatch]

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Generate Keystore
        run: |
          keytool -genkey -keyalg RSA -alias peditx -keystore newkeystore.keystore -storepass 2013 -validity 36000 -keysize 2048 -dname "CN=PeDitX, OU=PeDitX, O=PeDitXOS, L=fatih, S=istanbul, C=turkey" -keypass 2013
      
      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: newkeystore.keystore
